### DISCUSSION TITLE
SWC CSS parser and Codegen can preserve comments (rust)?

### DISCUSSION THREAD

**Discussion by shahryarjb** [swc-project/swc#10089] [Q&A]
Hello friends, in Rust I can not be able to keep (preserve) comments after changing CSS AST ! I wanted to ask is there any builtin feature to do this or for now SWC does not support it for CSS?

### My code sample:

```rust
pub fn parse(
    file_content: &str,
) -> Result<(Stylesheet, SingleThreadedComments, Lrc<SourceMap>), String> {
    let cm: Lrc<SourceMap> = Default::default();
    let fm = cm.new_source_file(FileName::Anon.into(), file_content.into());

    let comments = SingleThreadedComments::default();

    let lexer = Lexer::new(
        SourceFileInput::from(&*fm),
        Some(&comments),
        ParserConfig::default(),
    );

    let mut parser = Parser::new(lexer, ParserConfig::default());

    let stylesheet = match parser.parse_all() {
        Ok(s) => s,
        Err(_) => {
            return Err("Failed to parse CSS".to_string());
        }
    };

    Ok((stylesheet, comments, cm))
}
```

### And my css Codegen:

```rust
let mut output = String::new();
    {
        let mut writer = BasicCssWriter::new(&mut output, None, Default::default());
        let mut gen = CodeGenerator::new(&mut writer, CodegenConfig { minify: false });
        gen.emit(&stylesheet).expect("Failed to generate CSS");
    }

    Ok(output)
```

### And css Example:

```css
let css_code = r#"
            /* Top css comment */ 
            @import "reset.css";
            /* This file is for your main application CSS */
            body { color: black; /* Inner css comment */ }
            /* Bottom css comment */ 
        "#;

        let new_imports = r#"
            @import "theme.css";
            @import "reset.css";
            @import "custom.css";
        "#;

        let result = insert_import_to_ast(css_code, new_imports).unwrap();
        println!("{}", result);
```

## But it returns
```css
@import "theme.css";
@import "custom.css";
@import "reset.css";
body {
  color: black;
}
```

Thank you in advance
