### DISCUSSION TITLE
How do I turn off browser/vendor CSS prefixes (-webkit, etc.) in Styled JSX?

### DISCUSSION THREAD

**Discussion by arxpoetica** [swc-project/swc#7059] [Q&A]
This question is specific to the [@swc/plugin-styled-components](https://www.npmjs.com/package/@swc/plugin-styled-components) plugin. I can't figure out how to turn off CSS vendor/browser prefixes such as the following:

```css
.filters.jsx-1b179413de50d17c {
    display: -webkit-box;
    display: -webkit-flex;
    display: -moz-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-align: center;
    -webkit-align-items: center;
    -moz-box-align: center;
    -ms-flex-align: center;
    align-items: center;
}
```

That's a lot of noise when it's not needed. (I don't need it in my modern-browsers-only app.)

I realize this is an experimental plugin, and not fully baked, but even if I can do a pull request somewhere or if someone could point me in the right direction on how to fix it, would be much appreciated.

Trying to dig into the code, I've found this: https://github.com/swc-project/plugins/blob/main/packages/styled-jsx/transform/src/transform_css.rs#L83

But I'm not sure I understand what Rust is doing here.

FWIW, two cents, but I would think the default should be "off."
