### ISSUE TITLE
Bigint literal as a key in object literals cannot be parsed

### ISSUE THREAD

**Issue by magurotuna** [swc-project/swc#1173]
**Describe the bug**

If a property key in object literal is a bigint literal, swc emits an error.

```
SwcDiagnosticBuffer {
  "diagnostics": [
    "Unexpected token `bigint literal`. Expected identifier, string literal, numeric literal or [ for the computed key at deno_lint_test.tsx:1:12"
  ]
}
```

**Input code**

```ts
const x = { 1n: 42 };
```

**Config**

nothing
(executed via deno_lint)

**Expected behavior**

Successfully parsed

**Version**

```toml
swc_atoms = "0.2"
swc_common = "=0.10.4"
swc_ecmascript = { version = "=0.10.1", features = ["parser", "transforms", "utils", "visit"] }
```

**Additional context**

The input code comes from https://github.com/eslint/eslint/blob/v7.11.0/tests/lib/rules/no-dupe-keys.js#L49
Looking at this ESLint's code, it seems like using bigint literal as object key is available on ES2020.
On the other hand, tsc v4.0.2 cannot parse this either as you can see https://www.typescriptlang.org/play?target=99&ts=4.0.2#code/MYewdgzgLgBCBGArGBeGBvAUDGBGMAXDACwBMANJgL4DcQA

So I'm not sure if swc should parse this code. If you decide this won't be fixed for the time being, that's no problem 👍 

Relates to https://github.com/denoland/deno_lint/pull/406#discussion_r507111858
