### ISSUE TITLE
ecmascript print error

### ISSUE THREAD

**Issue by ije** [swc-project/swc#1499]
`P((h = (f.forEach(L), true)) => h` -> ` P((h = f.forEach(L), true) => h)`

in browser an error will be thrown:  

> Uncaught (in promise) SyntaxError: Invalid destructuring assignment target async function (async)

```toml
# cargo.toml

swc_common = { version = "0.10.13", features = ["sourcemap"] }
swc_ecmascript = { version = "0.28.1", features = ["codegen", "parser", "react", "transforms", "visit"] }
swc_ecma_transforms_typescript = "0.11.1"
swc_ecma_transforms_compat = "0.10.1"
swc_ecma_transforms_proposal = "0.10.1"
swc_ecma_ast = "0.41.0"
swc_ecma_visit = "0.27.0"
swc_ecma_utils = "0.32.0"
```
