### ISSUE TITLE
arrow functions with default generic parameters lead to (span.start <= span.end)

### ISSUE THREAD

**Issue by unbyte** [swc-project/swc#2040]
**Describe the bug**

arrow functions with default generic parameters lead to
```
thread 'main' panicked at 'internal error: entered unreachable code: assertion failed: (span.start <= span.end).
 start = $n, end = $n-1', **\swc_ecma_parser-0.66.0\src\parser\jsx.rs:99:38
```

**Input code**
```typescript
export const run = <T extends Function = () => any>(fn: T) => {
    fn()
}
```
**code**
```rust
let source_map = Rc::new(SourceMap::default());
let source_file = source_map.load_file(src)?;
let comments = SingleThreadedComments::default();

let syntax = Syntax::Typescript(TsConfig {
    tsx: true,
    decorators: true,
    dynamic_import: true,
    // stage 3:
    import_assertions: true,
    // others
    dts: false,
    no_early_errors: false,
})

let lexer = Lexer::new(
    syntax
    JscTarget::latest(),
    StringInput::from(&*source_file),
    Some(&comments),
);

let mut parser = Parser::new_from(lexer);

let program = parser
    .parse_program()
    .map_err(|e| AnyError::msg(e.into_kind().msg().to_string()))?;
```

**Expected behavior**

Parse successfully.

**Version**

```toml
swc_atoms = "0"
swc_common = "0"
swc_ecmascript = { version = "0", features = ["parser", "codegen", "visit", "transforms", "optimization"] }
```

**Additional context**
