### ISSUE TITLE
Use custom test manifest

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#3693]
## Better testing

We can create a toml file in `scripts/github` that describes how should we test each crate.

 - `ubuntu-latest` test is enabled for all crates.

 - We can test some crates in additional os by using `os.windows` and `os.macos`

This replaces https://github.com/swc-project/swc/blob/3c719f54e36fea24d6cf29b386ba62988079ee05/scripts/github/list-macos.txt and https://github.com/swc-project/swc/blob/3c719f54e36fea24d6cf29b386ba62988079ee05/scripts/github/list-windows.txt

 - `check` describes how should we check the compilability of crate.
   - We run compilability tests in workflow for each crates, instead of one huge `compilation` workflow.

e.g.

`tests.toml`:
```toml

[os.windows]
swc = true
# ...

[os.macos]
swc_plugin_runner = true

# We run this command from CI for each crates, instead of single `compilation` action.
[check]
swc_common = ["--feature-powerset", "--no-dev-deps"]


```
