### ISSUE TITLE
no method named `span_to_snippet` found for struct `Lrc<SourceMap>` in the current scope

### ISSUE THREAD

**Issue by mischnic** [swc-project/swc#4888]
```
error[E0599]: no method named `span_to_snippet` found for struct `Lrc<SourceMap>` in the current scope
    --> /Users/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_codegen-0.108.6/src/lib.rs:2231:35
     |
2231 |                     match self.cm.span_to_snippet(parent_node) {
     |                                   ^^^^^^^^^^^^^^^
     |
     = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
     |
8    | use swc_common::SourceMapper;
     |
help: there is an associated function with a similar name
     |
2231 |                     match self.cm.span_to_lines(parent_node) {
     |                                   ~~~~~~~~~~~~~
```

Using
```toml
swc_ecmascript = { version = "0.159.0", features = ["parser", "transforms", "module", "optimization", "react", "typescript", "utils", "visit", "codegen", "utils", "preset_env"] }
swc_common = { version = "0.18.8", features = ["tty-emitter", "sourcemap"] }
swc_atoms = "0.2.11"
```
and with everything bumped using `cargo update`
