### ISSUE TITLE
Support CSS `@container`

### ISSUE THREAD

**Issue by yisibl** [swc-project/swc#5410]
### Describe the feature

Container Query is a very important new CSS feature that browsers are actively implementing. Currently, Chrome 105+ and Safari 16+ are shipping.

- https://caniuse.com/css-container-queries
- Spec https://drafts.csswg.org/css-contain-3/
- Disallow and/not/or from <container-name> https://chromium-review.googlesource.com/c/chromium/src/+/3698402

```css
@supports ( container-type: size ) {
  @container ( width <= 150px ) {
    #inner {
      background-color: skyblue;
    }
  }
}
```
