### ISSUE TITLE
Exclude `layer` keyword in media query parser

### ISSUE THREAD

**Issue by yisibl** [swc-project/swc#5615]
### Describe the bug

According to recent spec, the <media-type> production does not include the keywords `only, not, and, or, layer`.

- Chrome fix it in: https://chromium-review.googlesource.com/c/chromium/src/+/3839085
- WPT test: http://wpt.live/css/mediaqueries/mq-invalid-media-type-layer-001.html

The following syntax is illegal:

```css
@media not layer {
    div { background-color: red; }
}

@media layer {
    div { background-color: pink; }
}
```
