### ISSUE TITLE
[css-minifier] missing `*` selector

### ISSUE THREAD

**Issue by yisibl** [swc-project/swc#5794]
### Describe the bug

```css
.row-cols-3 > * {
  -ms-flex: 0 0 33.333333%;
  flex: 0 0 33.333333%;
}

*,
*::before,
*::after {
  box-sizing: border-box;
  border: 1px solid #dee2e6;
}
```

SWC output

```css
.row-cols-3>{-ms-flex:0 0 33.333333%;flex:0 0 33.333333%},:before,:after{box-sizing:border-box;border:1px solid#dee2e6}
```

Test: https://github.com/Brooooooklyn/css-minify-comparation

### Expected behavior

-

### Version

0.123.3
