### ISSUE TITLE
[css-minifier]expand the static `calc()`

### ISSUE THREAD

**Issue by yisibl** [swc-project/swc#5860]
### Describe the feature

Often the expressions in calc() can be expanded further in order to reduce the number of bytes.

There is a lot of this CSS in [`animate.css`](https://github.com/animate-css/animate.css/blob/3235f27325ebc721fc4f8435d3c2d436642278bc/animate.css#L51-L56):

`animation-delay: calc(1s * 2) = animation-delay: 2s`

```css
.animate__animated.animate__delay-2s {
  -webkit-animation-delay: calc(1s * 2);
  animation-delay: calc(1s * 2);
  -webkit-animation-delay: calc(var(--animate-delay) * 2);
  animation-delay: calc(var(--animate-delay) * 2);
}
```

But if there are percentages in `calc()`, we have to treat them differently and not expand them. see https://github.com/evanw/esbuild/issues/1821
