### ISSUE TITLE
[css-minifier]Merge the same rules

### ISSUE THREAD

**Issue by yisibl** [swc-project/swc#5880]
### Describe the feature

I think this is a high priority and can greatly reduce the size of CSS files. Currently cssnano, lightningcss, esbuild are all supported.

## Input
```css
a:not([href]) {
  color: inherit;
  text-decoration: none
}

a:not([href]):hover {
  color: inherit;
  text-decoration: none
}
```

## swc output

```css
a:not([href]){color:inherit;text-decoration:none}a:not([href]):hover{color:inherit;text-decoration:none}
```

## Expected

```css
a:not([href]),a:not([href]):hover{color:inherit;text-decoration:none}
```
