### ISSUE TITLE
[css-minifier] Correctly parsed and compressed `<keyframes-name> = <string>`

### ISSUE THREAD

**Issue by yisibl** [swc-project/swc#5889]
## Input

```css
@keyframes "one two" {
  0% {
    left: 100px;
  }
}

@keyframes "none" {
  to {
    right: 100px;
  }
}

.foo {
  animation-name: "none", "unset", "one two";
}
```

## Actual  output

`@keyframes one two` is an invalid name and needs to be converted from a space to an **escape** character.

This WPT PR has more detailed test cases. https://github.com/web-platform-tests/wpt/pull/35903

```css
@keyframes one two{0%{left:100px}}@keyframes"none"{to{right:100px}}.foo{animation-name:"none","unset","one two"}
```

## Expected

```css
@keyframes one\ two{0%{left:100px}}@keyframes"none"{to{right:100px}}.foo{animation-name:"none","unset",one\ two}
```

### Version

0.125.9
