### ISSUE TITLE
[css-minifier]Check color value compression in all places

### ISSUE THREAD

**Issue by yisibl** [swc-project/swc#5903]
### Describe the bug

Need to compress CSS Gradients or other property values that contain colors.

### Input code

```typescript
.foo {
    background-image: image-set(linear-gradient(90deg, lightblue, pink) 1x, linear-gradient(90deg, pink, lightblue) 2x); 
}
```

### Expected behavior

```css
.bar{background-image:image-set(linear-gradient(90deg,#add8e6,pink) 1x,linear-gradient(90deg,pink,#add8e6) 2x)}
```

### Version

0.125.9

**Comment by alexander-akait** [comment]
I don't think it is a bug, because it is `<color>` type, so can be converted to any color, what is the problem here?

**Comment by yisibl** [comment]
Yes, there may be other functions that also contain `<color>`.

Parsing gradients has the added benefit of further compression, for example `to bottom` is the default value and can be removed.

**Comment by yisibl** [comment]
The colors in the custom properties are not compressed.

```css
:root {
    --primary-dark: lightblue;
    --white: white;
    --foo: #FFFFFF;
}
```

## Output

```css
:root{--primary-dark:lightblue;--white:white;--foo:#FFFFFF}
```

**Comment by alexander-akait** [comment]
I think we need do it under options, by spec custom properties can contain any information, even embedded languages, so by default it is unsafe to comoress

**Comment by yisibl** [comment]
Yes, it is indeed unsafe. lightningcss current practice is to compress only the values of non-color keywords. For example: `#FFFFFF`

One situation that needs further thought is whether custom properties can be safely compressed if they are defined by `@property`?

```css
@property ----primary-dark {
  syntax: "<color>";
  inherits: false;
  initial-value: #000;
}
```

**Comment by alexander-akait** [comment]
Yes, you are right, so we can implement the same logic using options (you will pass name of custom properties and type) and we can compress safely

**Comment by yisibl** [comment]
How about using comments similar to ESLint to control whether compression is turned on or not?

```css
/* swc-css-enable minify-color */
:root {
    --primary-dark: lightblue;
    --white: white;
    --foo: #FFFFFF;
}
```
