### ISSUE TITLE
`fold_import_decl` is not effective when target is not `EsVersion:Es2022`

### ISSUE THREAD

**Issue by hanayashiki** [swc-project/swc#5952]
### Describe the bug

Hi! I'm trying to use `swc::Compiler` directly in rust to do some transformation with my code. I'm trying to replace the import path with some custom string, but this doesn't seem to work when this target is ES2022 or any target other than ES5.

I implement `fold_import_decl` of trait `Fold`, and pass that trait to `process_js_with_custom_pass` to transform the code natively. `fold_import_decl` is actually called, but its return value seems to be ignored when the target is ES2022.

The minimal reproduction is as follow:

```rust
use std::{path::{PathBuf}, sync::Arc};

use swc::{self, config::Options, try_with_handler, HandlerOpts};

use swc_core::{
    common::{FilePathMapping, SourceMap},
};
use swc_ecma_visit::{
    noop_fold_type,
    swc_ecma_ast::{ImportDecl, Module, Script},
    Fold,
};

struct TransformImport {}

impl Fold for TransformImport {
    noop_fold_type!();

    fn fold_import_decl(&mut self, n: ImportDecl) -> ImportDecl {
        println!("fold_import_decl");
        if !n.src.value.starts_with("/")
            && !n.src.value.starts_with("./")
            && !n.src.value.starts_with("../")
        {
            let mut cloned = n.clone();
            cloned.src.value = "replaced".into();

            return cloned;
        }
        return n;
    }
}

struct Noop;
impl Fold for Noop {
    #[inline(always)]
    fn fold_module(&mut self, m: Module) -> Module {
        m
    }

    #[inline(always)]
    fn fold_script(&mut self, s: Script) -> Script {
        s
    }
}

fn main() {
    let cm = Arc::new(SourceMap::new(FilePathMapping::empty()));

    let fm = cm.new_source_file(
        swc_core::common::FileName::Real(PathBuf::from("main.tsx")),
        "import React from 'preact/compat'; console.log(React);".to_string(),
    );

    let c = swc::Compiler::new(cm.clone());

    let mut options = Options {
        ..Default::default()
    };

    options.config.jsc.target = Some(swc_ecma_visit::swc_ecma_ast::EsVersion::Es2022);

    let transform_import = TransformImport {};

    let output = try_with_handler(
        cm.clone(),
        HandlerOpts {
            ..Default::default()
        },
        |handler| {
            c.process_js_with_custom_pass(
                fm.clone(),
                None,
                handler,
                &options,
                |_, _| transform_import,
                |_, _| Noop {},
            )
        },
    );

    println!("{}", output.unwrap().code);
}

```

### Input code

```typescript
import React from 'preact/compat'; console.log(React);
```

### Config

```json
default with target: `es2022`
```

### Expected behavior

import React from 'replaced'; console.log(React);

### Actual behavior

```
import React from 'preact/compat';
console.log(React);
```

### Version

See additional context

### Additional context

```toml
# Cargo.toml

[package]
name = "hello-rocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
swc = "0.229.1"
swc_config = "0.1.2"
swc_core = { version = "0.27.1", features = [
  "ecma_ast",
  "common_concurrent",
  "bundler",
  "ecma_loader",
  "base_node",
  "base_concurrent",
] }
swc_ecma_loader = "0.41.0"
swc_ecma_visit = "0.80.0"

[profile.release]
debug = true
lto = true

```
