### ISSUE TITLE
Unnecessary lower the `PX` in css

### ISSUE THREAD

**Issue by IWANABETHATGUY** [swc-project/swc#6776]
### Describe the bug

```css
.rule {
  margin: 0.75rem calc(100% - 14PX);
  height: calc(100% - 1.25rem);
  font-size: 12Px;
  line-height: 1rem;
}
```
We use this `Uppercase` px trick to disallow `postcss-px2rem` transform `px` to `rem`, but `swc-css` will lowercase `px` anyway, this would cause unexpected behavior when trying to use `postcss-px2rem` with `swc-css`. Also this transform is 
a little redundant because browser will treat `PX` and `px` as same `unit`.

**Code snippet**
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    .test {
      width: 100px;
      height: 100px;
      background-color: red;
    }
  </style>
</head>
<div class="test"></div>
<body>
</body>
</html>
```
## px
![image](https://user-images.githubusercontent.com/17974631/211475061-09f061b0-91d7-4ceb-bd2f-db05d38cae24.png)

## PX
![image](https://user-images.githubusercontent.com/17974631/211475156-74985aa3-4a04-48a0-9812-16e04d970780.png)

### Input code

```typescript
.rule {
  margin: 0.75rem calc(100% - 14PX);
  height: calc(100% - 1.25rem);
  font-size: 12Px;
  line-height: 1rem;
}
```

### Config

```json
No
```

### Expected behavior

```css
.rule {
  margin: 0.75rem calc(100% - 14PX);
  height: calc(100% - 1.25rem);
  font-size: 12Px;
  line-height: 1rem;
}
```

### Actual behavior

```css
.rule {
  margin: 0.75rem calc(100% - 14px);
  height: calc(100% - 1.25rem);
  font-size: 12px;
  line-height: 1rem;
}
```

### Version

swc_core 0.53.1
