### ISSUE TITLE
Support stable rustc (again)

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#7039]
### Describe the feature

I used `box_patterns` while working on https://github.com/swc-project/swc/pull/7041 because refactoring for `box_patterns` is much bigger than the PR itself, and I wanted to align the version of `swc_core` between projects in a short time.

But we should support stable rustc.

**Comment by stevefan1999-personal** [comment]
Let's open it back shall we, look at the issues I mentioned

**Comment by kdy1** [comment]
@stevefan1999-personal Please list the crate you are trying to use. This issue is closed because crates I want to support stable rustc are all fixed

**Comment by ije** [comment]
i can not build swc with stable rustc

```
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/x/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_minifier-0.180.16/src/lib.rs:39:1
   |
39 | #![feature(box_patterns)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `swc_ecma_minifier` due to previous error
```

used crates:

```toml
swc_atoms = "0.5.3"
swc_common = { version = "0.31.4", features = ["sourcemap", "perf"] }
swc_ecmascript = { version = "0.227.16", features = ["codegen", "parser", "utils", "visit"] }
swc_ecma_transforms = { version = "0.217.14", features = ["proposal", "typescript", "react", "compat", "optimization" ] }
swc_ecma_minifier = "0.180.16"
```

**ps, i'm using rustc 1.68.2 (9eb3afe9e 2023-03-27)**
