### ISSUE TITLE
[css modules] Using `:global` and Attribute Selector at the same time breaks output

### ISSUE THREAD

**Issue by Thiry1** [swc-project/swc#7669]
### Describe the bug

Using `:global` and Attribute Selector at the same time breaks output.
Transfered from https://github.com/web-infra-dev/rspack/issues/3777

### Input code

```typescript
.class:global[data-x=true] > .inner {
    color: red;
}

.class[data-x=true]:global > .inner {
    color: yellow;
}
```

### Config

```json
none
```

### Expected behavior

```css
.__local__class[data-x=true] > .inner {
  color: red;
}
.__local__class[data-x=true] > .inner {
  color: yellow;
}
```

### Actual behavior

```css
/* attribute selector is disappear */
.__local__class > .inner {
  color: red;
}
.__local__class[data-x=true] > .inner {
  color: yellow;
}
```

### Version

1.3.70
