### ISSUE TITLE
[CSS] Deduplication of minifier is not smart enough

### ISSUE THREAD

**Issue by hyf0** [swc-project/swc#7672]
### Describe the feature

For input
```css
body {
  color: red;
}

body {
  color: red;
}
```
cssnano will discard duplicated rules.

https://cssnano.co/playground/

![image](https://github.com/swc-project/swc/assets/49502170/1765f07e-0bac-4ca5-9b1c-dbdbd773eca0)

### Additional context

Not an urgent request. Just want to bring it up.

**Comment by kdy1** [comment]
It's already supported by the `swc_css_minifier`

**Comment by hyf0** [comment]
@kdy1 I tested locally.

A complicated case like this isn't discarded.

```css
body {
  color: red;
}

h1 {
  color: red;
}

body {
  color: red;
}
```

CSSnano outout
![image](https://github.com/swc-project/swc/assets/49502170/eb995b46-15b2-4d7e-b5ff-5df18f653402)
