### ISSUE TITLE
[css/modules] composes fails due to order of class names

### ISSUE THREAD

**Issue by Thiry1** [swc-project/swc#7910]
### Describe the bug

composes fails due to order of class names.

### Input code

```css
.child-class1 {
    color: red;
}
.root-class {
    composes: child-class1;
    composes: child-class2;
}
.child-class2 {
    color: green;
}
```

### Expected behavior

```json
{
  "child-class1": [
    {
      "type": "local",
      "name": "__local__child-class1"
    }
  ],
  "root-class": [
    {
      "type": "local",
      "name": "__local__root-class"
    },
    {
      "type": "local",
      "name": "__local__child-class1"
    },
    {
      "type": "local",
      "name": "__local__child-class2"
    }
  ],
  "child-class2": [
    {
      "type": "local",
      "name": "__local__child-class2"
    }
  ]
}

```

### Actual behavior

```diff
{
  "child-class1": [
    {
      "type": "local",
      "name": "__local__child-class1"
    }
  ],
  "root-class": [
    {
      "type": "local",
      "name": "__local__root-class"
    },
    {
      "type": "local",
      "name": "__local__child-class1"
-   },
-   {
-     "type": "local",
-     "name": "__local__child-class2"
    }
  ],
  "child-class2": [
    {
      "type": "local",
      "name": "__local__child-class2"
    }
  ]
}


```

### Version

1.3.82
