### ISSUE TITLE
swc_css parse `filter: progid:DXImageTransform.Microsoft.Matrix(x1, x2)` error

### ISSUE THREAD

**Issue by wre232114** [swc-project/swc#8894]
### Describe the bug

following code can not be parsed by swc_css_parser:

```css
leaflet-oldie .leaflet-popup-tip {
	filter: progid:DXImageTransform.Microsoft.Matrix(M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678);
	}
```

### Input code

```typescript
leaflet-oldie .leaflet-popup-tip {
	filter: progid:DXImageTransform.Microsoft.Matrix(M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678);
	}
```

### Playground link (or link to the minimal reproduction)

no

### Expected behavior

parse the legacy css code sucessfully

### Version

1.4.17
