### ISSUE TITLE
`swc_css_parser` throws exception when parsing `oklch`/`oklab` color function with certain arguments

### ISSUE THREAD

**Issue by Dwlad90** [swc-project/swc#9766]
### Describe the bug

With certain arguments it is not possible to parse the CSS function `oklch`, as a result of which the following error occurs:

- Expected 'e', 'pi', 'infinity', '-infinity' or 'NaN', ident tokens
- Called `Result::unwrap()` on an `Err` value:   x Unexpected value

The same problem also occur with the function `oklab`.

### Input code

```css
* { color: oklch(from green l c h / 0.5) }

* { color: oklch(from #0000FF calc(l + 0.1) c h) }

* { color: oklch(from #000 calc(l + 0.2) c h) }

* { background-image: radial-gradient(circle at 0% 0%, oklch(from var(--colors-tile-background) calc(l + 0.1) calc(c + 0.2) h) 0, transparent 15% ), radial-gradient( circle at 80% 100%, oklch(from var(--colors-tile-background) calc(l - 0.25) calc(c + 0.01) h) 0, transparent 30% ), linear-gradient( 45deg, var(--colors-tile-background) 0%, oklch(from var(--colors-tile-background) calc(l - 0.1) calc(c + 0.3) h) 100% ) }

* { box-shadow: 0 0 calc(var(--x1gppajd) * 10) 0 oklch(from var(--colors-tile-background) l c h / 0.15) }

* { color: oklch(from #021310 l c h / 0.9) }

* { color: oklab(from green l a b / 0.5) }

* { color: oklab(from #0000FF calc(l + 0.1) a b / calc(alpha * 0.9)) }
```

### Playground link (or link to the minimal reproduction)

https://github.com/Dwlad90/swc/tree/bug/oklch

### SWC Info output

```zsh
---- pass_tests__fixture__value__color__input_css stdout ----
Input: ~/Projects/swc/crates/swc_css_parser/tests/fixture/value/color/input.css
thread 'pass_tests__fixture__value__color__input_css' panicked at crates/swc_css_parser/tests/fixture.rs:77:6:
called `Result::unwrap()` on an `Err` value:   x Expected 'e', 'pi', 'infinity', '-infinity' or 'NaN', ident tokens
    ,-[$DIR/tests/fixture/value/color/input.css:97:1]
 96 |     color: oklab(var(--a) var(--b) var(--c));
 97 |     color: oklab(from #0000FF calc(l + 0.1) a b / calc(alpha * 0.9));
    :                                    ^
 98 |     color: oklab(from green l a b / 0.5)
    `----
  x Expected 'none' value of an ident token
    ,-[$DIR/tests/fixture/value/color/input.css:97:1]
 96 |     color: oklab(var(--a) var(--b) var(--c));
 97 |     color: oklab(from #0000FF calc(l + 0.1) a b / calc(alpha * 0.9));
    :                                             ^
 98 |     color: oklab(from green l a b / 0.5)
    `----
  x Expected 'none' value of an ident token
    ,-[$DIR/tests/fixture/value/color/input.css:98:1]
 97 |     color: oklab(from #0000FF calc(l + 0.1) a b / calc(alpha * 0.9));
 98 |     color: oklab(from green l a b / 0.5)
    :                             ^
 99 | }
    `----
  x Expected 'e', 'pi', 'infinity', '-infinity' or 'NaN', ident tokens
     ,-[$DIR/tests/fixture/value/color/input.css:106:1]
 105 |     color: oklch(var(--a) var(--b) var(--c) / var(--d));
 106 |     color: oklch(from #000 calc(l + 0.2) c h);
     :                                 ^
 107 |     color: oklch(from #021310 l c h / 0.9);
     `----
  x Expected 'none' value of an ident token
     ,-[$DIR/tests/fixture/value/color/input.css:106:1]
 105 |     color: oklch(var(--a) var(--b) var(--c) / var(--d));
 106 |     color: oklch(from #000 calc(l + 0.2) c h);
     :                                          ^
 107 |     color: oklch(from #021310 l c h / 0.9);
     `----
  x Expected 'none' value of an ident token
     ,-[$DIR/tests/fixture/value/color/input.css:107:1]
 106 |     color: oklch(from #000 calc(l + 0.2) c h);
 107 |     color: oklch(from #021310 l c h / 0.9);
     :                               ^
 108 | }
     `----

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    pass_tests__fixture__value__color__input_css
```

### Expected behavior

Correct parsing to valid AST

### Version

4.0.0

### Additional context

Link to [SWC CSS Playground](https://swc-css.netlify.app/?code=eJydku1OgzAUhv_vKt7ELAGk2g5JlAvYfRxKBVxHSUFdYrx3W-YCKLplpAmBvB9P2xPhA9JoYzOYnZZV8GzNHqVVqoGGRIV78Ls0xOdqFS1qb7h7tltI0jLQuHVyEXrnGc_UsJkbcpK70prXpmD1nkqVwVJRk2alf6umD2RtpVagHnztVjwNfyMbMDaUdqyvtWJjXvgT03_JE4Mj4DF6S03XknU9EOkaYfyrHmP_owMQ_BoE5kvTGQMXSxAJHyB03SiyE4iHtFBlfKbsWrL54SQDl98nxlsyB9ZVVJj3DBzf93nMP4iybenFJUbO5CAuRxiHTvw_dRuRCD6RPy2oKZ_PMyH_c55P2uV5PjqHf6TbitzGfKXL-QLcp_iM)

To reproduce the error, please run `cargo test -p swc_css_parser` in the provided repo

Thanks to @HQ92 for finding the bug,
Original issue: https://github.com/Dwlad90/stylex-swc-plugin/issues/119
